name: CI

on:
  push:
    branches:
      - master
      - 'features/**'
  pull_request:
    branches:
      - master

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # <<< install Poetry before calling make install-dev >>>
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies (dev)
        run: make install-dev

      - name: Lint with Ruff
        run: make lint

      - name: Format check with Black
        run: poetry run black --check backend frontend scripts

      - name: Run tests
        run: make test

  build-docker:
    name: Build Docker Image
    needs: lint-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: make docker-build