# ===== These configurtions must be applied to the settings of the streamlit cloud
DEPLOYMENT_MODE = "cloud"
IN_MEMORY=true
GROQ_API_KEY="gsk_XXXXXX" # Your Groq API key
DEBUG_MODE = false
PYTHONPATH = "."
